[workspace]
resolver = "2"
members = [
    "ts_core",
    "cli",
    "simulation",
]

[workspace.dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
